import type { FormatConfigState } from "@/types/tournament";

export const createEmptyFormatConfig = (): FormatConfigState => ({
  name: "",
  type: "HYBRID",
  minTeams: 4,
  maxTeams: 24,
  description: "",
  matchDuration: 15,
  hasWildcards: false,
  rankingCriteria: ["matchPoints", "scoreDifference", "headToHead"],
  groupsCount: 6,
  teamsPerGroup: 4,
  roundRobinLegs: 1,
  qualifiersPerGroup: 2,
  wildcardCount: 0,
  winPoints: 1,
  drawPoints: 0,
  lossPoints: 0,
  groupTargetScore: 11,
  groupChangeSideAt: 6,
  finalTargetScore: 15,
  finalChangeSideAt: 8,
  maxWaitMinutes: 10,
  timeoutCount: 1,
  timeoutSeconds: 180,
  branchRules: "",
  refereeRules: "",
  uniformRules: "",
  customRules: "",
});
