import type { TournamentOperationsState, TournamentRuleRef } from "@/types/orgTournamentMgmt";

export const createEmptyTournamentOperations = (): TournamentOperationsState => ({
  registrationMode: "system",
  registrationFormUrl: "",
  zaloGroupUrl: "",
  maxRegistrations: 0,
  registrationInstructions: "",
  supportContacts: "",
  feeIncludes: "",
  bankName: "",
  accountName: "",
  accountNumber: "",
  transferContent: "",
  paymentInstructions: "",
  refundPolicy: "",
  mediaConsent: false,
  mediaUsageTerms: "",
  logo: "",
  banner: [],
  paymentQR: "",
  hasGala: false,
  galaStart: "",
  galaEnd: "",
  galaVenue: "",
  galaDescription: "",
  sponsorContact: "",
  sponsorTiers: [],
});

export const createEmptyTournamentRule = (sport = "Pickleball"): TournamentRuleRef => ({
  sport,
  categoryRuleId: "",
  categoryName: "",
  source: "system",
  maxTeams: 24,
  feePerAthlete: 0,
  categories: [],
  itemName: "",
  itemDescription: "",
  inheritTimeline: false,
  inheritLocation: false,
  inheritMedia: false,
  inheritPrizes: false,
  operations: createEmptyTournamentOperations(),
});
