import { useEffect, useState, type FormEvent } from "react";
import { MapPin, Pencil, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import api, { getApiErrorMessage } from "@/libs/axios";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
type Court = { _id: string; name: string; location: string; status: "empty" | "busy" | "maintenance" | "inactived"; sportTypes?: string[] };
const blank = { name: "", location: "", sportTypes: "", status: "empty" as Court["status"] };
export default function AdminCourtsPage() {
  const [courts,setCourts]=useState<Court[]>([]); const [form,setForm]=useState(blank); const [editingId,setEditingId]=useState<string|null>(null); const [loading,setLoading]=useState(true);
  const load=async()=>{setLoading(true);try{const r=await api.get<{data:Court[]}>("/courts");setCourts(r.data.data||[]);}catch(e){toast.error(getApiErrorMessage(e,"Không thể tải danh sách sân."));}finally{setLoading(false);}};
  useEffect(()=>{void load();},[]);
  const submit=async(event:FormEvent)=>{event.preventDefault();const payload={...form,sportTypes:form.sportTypes.split(",").map(v=>v.trim()).filter(Boolean)};try{if(editingId)await api.put(`/courts/${editingId}`,payload);else await api.post("/courts",payload);toast.success(editingId?"Đã cập nhật sân.":"Đã tạo sân.");setEditingId(null);setForm(blank);await load();}catch(e){toast.error(getApiErrorMessage(e,"Không thể lưu sân."));}};
  return <div className="mx-auto max-w-6xl space-y-6"><header><p className="text-sm font-bold uppercase text-primary">Quản trị nền tảng</p><h1 className="mt-2 text-3xl font-black">Danh mục sân thi đấu</h1><p className="mt-2 text-muted-foreground">Admin quản lý sân dùng chung. Ban tổ chức chỉ chọn sân khi xếp lịch hoặc phân công trận.</p></header><form onSubmit={submit} className="grid gap-3 rounded-2xl border bg-card p-5 md:grid-cols-5"><Input required aria-label="Tên sân" placeholder="Tên sân" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Input required aria-label="Địa điểm" placeholder="Địa điểm" value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/><Input aria-label="Môn phù hợp" placeholder="Các môn, cách nhau dấu phẩy" value={form.sportTypes} onChange={e=>setForm({...form,sportTypes:e.target.value})}/><select aria-label="Trạng thái" className="h-10 rounded-md border bg-background px-3" value={form.status} onChange={e=>setForm({...form,status:e.target.value as Court["status"]})}><option value="empty">Sẵn sàng</option><option value="busy">Đang dùng</option><option value="maintenance">Bảo trì</option><option value="inactived">Ngừng hoạt động</option></select><Button><Plus className="size-4"/>{editingId?"Lưu":"Thêm sân"}</Button></form><div className="overflow-hidden rounded-2xl border bg-card">{loading?<p className="p-6">Đang tải...</p>:courts.length===0?<p className="p-6 text-muted-foreground">Chưa có sân thi đấu.</p>:courts.map(c=><div key={c._id} className="flex flex-col gap-3 border-b p-4 last:border-0 sm:flex-row sm:items-center"><MapPin className="size-5 text-primary"/><div className="min-w-0 flex-1"><p className="font-bold">{c.name}</p><p className="text-sm text-muted-foreground">{c.location} · {c.sportTypes?.join(", ")||"Mọi môn"}</p></div><Button variant="outline" size="sm" onClick={()=>{setEditingId(c._id);setForm({name:c.name,location:c.location,sportTypes:c.sportTypes?.join(", ")||"",status:c.status});}}><Pencil className="size-4"/>Sửa</Button><Button variant="destructive" size="sm" onClick={async()=>{if(!confirm(`Xóa sân ${c.name}?`))return;try{await api.delete(`/courts/${c._id}`);await load();}catch(e){toast.error(getApiErrorMessage(e,"Không thể xóa sân."));}}}><Trash2 className="size-4"/>Xóa</Button></div>)}</div></div>;
}
